# Generated by Django 5.0.4 on 2024-05-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_description_alter_mailing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='не обязательное поле', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='не обязательное поле', null=True, verbose_name='Дата начала'),
        ),
    ]
